- name: Update apt-cache
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Sqllite package
  package:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop: "{{ sqllite_packages }}"
  become: yes


