---
- name: Update apt-cache
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Apache
  become: yes
  apt:
    name: "{{ apache_packages }}"
    state: present

- name: Configure Apache ports
  become: yes
  lineinfile:
    dest: "{{ apache_server_root }}/ports.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    mode: 0644
  loop: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes