apache_packages:
  - apache2
  - apache2-utils

apache_service: apache2
apache_server_root: /etc/apache2
apache_listen_port: 80

apache_ports_configuration_items:
  - {
    regexp: "^Listen ",
    line: "Listen {{ apache_listen_port }}"
  }